# Generated by Django 3.1.1 on 2020-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('idUsuario', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
