# Generated by Django 3.1.1 on 2020-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoIdentificacion', models.IntegerField()),
                ('lugarNacimiento', models.CharField(max_length=50)),
                ('nombreCompletoAcudiente', models.CharField(max_length=50)),
                ('tipoIdentificaionAcudiente', models.CharField(max_length=50)),
                ('numeroIdentificacionAcudiente', models.IntegerField()),
                ('numeroTelefonicoAcudiente', models.IntegerField()),
                ('correoElectroncoAcudiente', models.CharField(max_length=50)),
                ('idInicioSesion', models.IntegerField()),
            ],
        ),
    ]
