# Generated by Django 3.1.1 on 2020-09-11 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccionResidencia',
            field=models.CharField(default='abcd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numeroIdentificacion',
            field=models.IntegerField(default=122344555),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='idInicioSesion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipoIdentificacion',
            field=models.CharField(max_length=50),
        ),
    ]
