# Generated by Django 3.1.1 on 2020-09-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20200911_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='urlFotografia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
