# Generated by Django 3.1.1 on 2020-10-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_estudiante_urlfotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroIdentificacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroIdentificacionAcudiente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroTelefonicoAcudiente',
            field=models.CharField(max_length=50),
        ),
    ]
