# Generated by Django 3.1.1 on 2020-10-05 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('docente', models.CharField(max_length=50)),
                ('introduccion', models.CharField(max_length=500)),
                ('estudiantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('talleres', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('evaluaciones', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('respuestasTalleres', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('respuestasEvaluaciones', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('asistencias', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('foro', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
        ),
    ]
