# Generated by Django 3.1.1 on 2020-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_auto_20201005_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='introduccion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
