# Generated by Django 3.1.1 on 2020-09-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipoIdentificacion', models.CharField(max_length=50)),
                ('numeroIdentificacion', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('lugarNacimiento', models.CharField(max_length=50)),
                ('correoElectronco', models.CharField(max_length=50)),
                ('direccionResidencia', models.CharField(max_length=50)),
                ('numeroCelular', models.IntegerField()),
                ('numeroTelefonoFijo', models.IntegerField()),
                ('idInicioSesion', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('urlFotografia', models.CharField(max_length=50)),
            ],
        ),
    ]
