# Generated by Django 3.1.1 on 2020-10-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_auto_20201005_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='contrasena',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='correoElectronco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='direccionResidencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fechaNacimiento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='idInicioSesion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='lugarNacimiento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numeroCelular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numeroIdentificacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numeroTelefonoFijo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipoIdentificacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='urlFotografia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
