# Generated by Django 3.1.1 on 2020-10-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_auto_20201006_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='contrasena',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='idInicioSesion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='lugarNacimiento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numeroIdentificacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numeroTelefonoFijo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipoIdentificacion',
            field=models.CharField(max_length=50),
        ),
    ]
