# Generated by Django 3.1.1 on 2020-10-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_auto_20201006_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='numeroCelular',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numeroTelefonoFijo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
